### PR TITLE
Disturbance_V3: Approval Cancel, Suspension, Surrender and Reinstate functionality

### PR DESCRIPTION
**Pull request by preranaandure**
Approval Cancel functionality

---
This change is [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)

### CODE REVIEW

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/templates/disturbance/emails/approval_cancel_notification.txt, line 4 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4C93h0LNYCJLprvSU:-LB4C93h0LNYCJLprvSV:blknyv) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/disturbance/components/approvals/templates/disturbance/emails/approval_cancel_notification.txt#L4)):*
> ```
> 
> {%  block content %}
>     Your Approval has been expired:
> ```

Should be "Your Approval has been cancelled:"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/templates/disturbance/emails/approval_suspend_notification.html, line 4 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4CO1W83xp0ZdaIRZJ:-LB4CO1W83xp0ZdaIRZK:b-fhi6b7) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/disturbance/components/approvals/templates/disturbance/emails/approval_suspend_notification.html#L4)):*
> ```HTML
> 
> {%  block content %}
>     <p>Your Approval has been cancelled:</p>
> ```

Should be "Your Approval has been suspended:"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/templates/disturbance/emails/approval_suspend_notification.txt, line 4 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4CRoh2uF6J670pkTj:-LB4CRoh2uF6J670pkTk:b-fhi6b7) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/disturbance/components/approvals/templates/disturbance/emails/approval_suspend_notification.txt#L4)):*
> ```
> 
> {%  block content %}
>     Your Approval has been expired:
> ```

Should be "Your Approval has been suspended:"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/email.py, line 26 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4CdPx4cJKLh7mp0x1:-LB4CdPx4cJKLh7mp0x2:b-fhif7j) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/disturbance/components/approvals/email.py#L26)):*
> ```Python
> 
> class ApprovalSuspendNotificationEmail(TemplateEmailBase):
>     subject = 'Your Approval has been suspend.'
> ```

Should be "Your Approval has been suspended."?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[ledger/accounts/migrations/0012_auto_20180118_1505.py, line 11 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4Cpgt73i8Up4nhJ_Q:-LB4Cpgt73i8Up4nhJ_R:b-29b36u) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/ledger/accounts/migrations/0012_auto_20180118_1505.py#L11)):*
> ```Python
> 
>     dependencies = [
>         ('accounts', '0012_auto_20171228_1221'),
> ```

Please revert this change, this particular migration was replaced during the merge into mainline

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by dbca-asi** [comment]
Yep, I’ve already made changes in another commit.

**Comment by scottp-dpaw** [comment]
*[ledger/accounts/migrations/0012_auto_20180118_1505.py, line 11 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4Cpgt73i8Up4nhJ_Q:-LB4EL305rivqWaXtBAt:b-cpjju6) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/ledger/accounts/migrations/0012_auto_20180118_1505.py#L11)):*
<details><summary><i>Previously, scottp-dpaw wrote…</i></summary><blockquote>

Please revert this change, this particular migration was replaced during the merge into mainline
</blockquote></details>

Oh wait I see this push is to the disturbances_v3 branch... let me have a think

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
Could you please push the new commits? Thanks.

**Comment by scottp-dpaw** [comment]
*[ledger/accounts/migrations/0012_auto_20180118_1505.py, line 11 at r1](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4Cpgt73i8Up4nhJ_Q:-LB4bJKQ6tV--VvjopOh:b-tfz3le) ([raw file](https://github.com/dbca-wa/ledger/blob/79469e23f0eb70a66f1bdb5967044d76734c4ced/ledger/accounts/migrations/0012_auto_20180118_1505.py#L11)):*
<details><summary><i>Previously, scottp-dpaw wrote…</i></summary><blockquote>

Oh wait I see this push is to the disturbances_v3 branch... let me have a think
</blockquote></details>

Should be sorted by the rebase

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/templates/disturbance/emails/approval_reinstate_notification.html, line 4 at r2](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4e9qf0DXh8dqe8gyN:-LB4e9qf0DXh8dqe8gyO:b9shc9g) ([raw file](https://github.com/dbca-wa/ledger/blob/d7d4ddcae879ecaf7376fef292676b91789a3b88/disturbance/components/approvals/templates/disturbance/emails/approval_reinstate_notification.html#L4)):*
> ```HTML
> 
> {%  block content %}
>     <p>Your Approval has been reinstate:</p>
> ```

Should be Your Approval has been reinstated

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Comment by scottp-dpaw** [comment]
*[disturbance/components/approvals/templates/disturbance/emails/approval_reinstate_notification.txt, line 4 at r2](https://reviewable.io/reviews/dbca-wa/ledger/280#-LB4eGbU4UVdWrRQguNm:-LB4eGbU4UVdWrRQguNn:b9shc9g) ([raw file](https://github.com/dbca-wa/ledger/blob/d7d4ddcae879ecaf7376fef292676b91789a3b88/disturbance/components/approvals/templates/disturbance/emails/approval_reinstate_notification.txt#L4)):*
> ```
> 
> {%  block content %}
>     Your Approval has been reinstate:
> ```

Should be Your Approval has been reinstated

---


*Comments from [Reviewable](https://reviewable.io/reviews/dbca-wa/ledger/280)*

**Pull request merged**
